language: node_js
node_js:
  - "0.11"
  - "0.10.27"
  - "0.10.26"
  - "0.10"

matrix:
  allow_failures:
    - node_js: 0.11

notifications:
  email:
    - mosconfabrizio@gmail.com

before_install:
  - NVM_NODEJS_ORG_MIRROR=http://nodejs.org/dist nvm install ${TRAVIS_NODE_VERSION}
  - node --version
  - npm --version

cache:
  directories:
    - node_modules

script: "npm test"
